Fixed CI Deployment
Followup to
https://github.com/microsoft/planetary-computer-tasks/actions/runs/5336427981/jobs/9672348147,
which failed with

```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

1
  Enter a value:
Error: Process completed with exit code 1.
```

We need to pass `-y` to auto-approve.