Update `helm/kind-action`  version (#202)
* Update helm/kind-action version

This bumps the version of helm/kind-action to 1.5. In
https://github.com/microsoft/planetary-computer-tasks/actions/runs/4941001231/jobs/8833187352?pr=201,
we're running into an incompatibility between the installed Kubernetes
version and the version required by KEDA:

```
===== KEDA =======
+ helm repo add kedacore https://kedacore.github.io/charts
"kedacore" has been added to your repositories
+ helm upgrade --install keda kedacore/keda -n keda --create-namespace
--wait --timeout 2m0s
Release "keda" does not exist. Installing it now.
Error: chart requires kubeVersion: >=v1.24.0-0 which is incompatible
with Kubernetes v1.23.4
Error: Process completed with exit code 1.
```