[noaa-mrms-qpe] Use pre-built Dockerfile (#94)
* [noaa-mrms-qpe] Use pre-built Dockerfile

Our nightly job had some failures, ending with

```
  File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 454, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```

i.e. our runtime pip install failed. Moving this to a pre-built container with all the dependencies

* [batch]: Update vm for s2 pool

Move from D3_V2 to D4_V4.